### ISSUE TITLE
Cannot import trace from tensorflow.python.profiler

### ISSUE THREAD

**Issue by n-garc** [google-research/electra#132]
Just installed tensorflow 1.15 using conda, getting this error when attempting to run the pre-training command provided in the quickstart section of the readme.

```
Traceback (most recent call last):
  File "electra/run_pretraining.py", line 29, in <module>
    from model import modeling
  File "electra\model\modeling.py", line 33, in <module>
    from tensorflow.contrib import layers as contrib_layers
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow_core\contrib\__init__.py", line 39, in <module>
    from tensorflow.contrib import compiler
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow_core\contrib\compiler\__init__.py", line 21, in <module>
    from tensorflow.contrib.compiler import jit
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow_core\contrib\compiler\__init__.py", line 22, in <module>
    from tensorflow.contrib.compiler import xla
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow_core\contrib\compiler\xla.py", line 22, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\estimator\model_fn.py", line 26, in <module>
    from tensorflow_estimator.python.estimator import model_fn
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\_api\v1\estimator\experimental\__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\canned\dnn.py", line 27, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 36, in <module>
    from tensorflow.python.profiler import trace
ImportError: cannot import name 'trace' from 'tensorflow.python.profiler' (C:\Users\<user>\anaconda3\envs\tensorflow1.15\lib\site-packages\tensorflow_core\python\profiler\__init__.py)
```

**Comment by n-garc** [comment]
Huh. Installed via pip and it seems to be working.

**Comment by 2076263413** [comment]
Hello,can i ask how to deal with it?

**Comment by wxuyec** [comment]
just run "pip install tensorflow" in the enviroment

**Comment by annulen** [comment]
>just run "pip install tensorflow" in the enviroment

I think it should be explicitly suggested in XLA error message of just `Can't import tensorflow.python.profiler.trace`. It should also be documented in https://jax.readthedocs.io/en/latest/profiling.html and https://jax.readthedocs.io/en/latest/_autosummary/jax.profiler.trace.html.

Alternatively, profiler component could be extracted to separate package to avoid tensorflow dependency. If it turns out to be small it could be even installed by default as dependency.
