### ISSUE TITLE
keyerror:loss.

### ISSUE THREAD

**Issue by fenfaqingnian** [google-research/electra#76]
Traceback (most recent call last):
  File "run_finetuning.py", line 323, in <module>
    main()
  File "run_finetuning.py", line 319, in main
    args.model_name, args.data_dir, **hparams))
  File "run_finetuning.py", line 275, in run_finetuning
    results.append(model_runner.evaluate())
  File "run_finetuning.py", line 186, in evaluate
    return {task.name: self.evaluate_task(task) for task in self._tasks}
  File "run_finetuning.py", line 186, in <dictcomp>
    return {task.name: self.evaluate_task(task) for task in self._tasks}
  File "run_finetuning.py", line 198, in evaluate_task
    scorer.update(r[task.name])
  File "/code/electra-master/finetune/classification/classification_metrics.py", line 43, in update
    self._total_loss += results['loss']
KeyError: 'loss'

**Comment by clarkkev** [comment]
Can you provide some more detail? What task were you fine-tuning on and what command did you run?

**Comment by jgung** [comment]
@fenfaqingnian I observed the same error when I created a custom classification task with an underscore `_` in the name. This seems to be a reserved delimeter. After removing the underscore from the task name, the error went away.

**Comment by prokok** [comment]
> @fenfaqingnian I observed the same error when I created a custom classification task with an underscore `_` in the name. This seems to be a reserved delimeter. After removing the underscore from the task name, the error went away.

spent several hours to figure it out. thx!
